// Generated by nuxt-api-party
import type { $Api, $OpenApi, ApiFetchOptions } from '../../node_modules/nuxt-api-party/dist/runtime/composables/$api'
import type { UseApiData, UseOpenApiData, UseApiDataOptions } from '../../node_modules/nuxt-api-party/dist/runtime/composables/useApiData'



export type { $Api, $OpenApi, ApiFetchOptions, UseApiData, UseOpenApiData, UseApiDataOptions }

export declare const $jsonPlaceholder: $Api
export declare const useJsonPlaceholderData: UseApiData
